# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /global/homes/n/natalieb/TrackPerfWorkspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /global/homes/n/natalieb/TrackPerfWorkspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(CMAKE_COMMAND) -E cmake_progress_start /global/homes/n/natalieb/TrackPerfWorkspace/CMakeFiles /global/homes/n/natalieb/TrackPerfWorkspace/packages/TrackPerf//CMakeFiles/progress.marks
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 packages/TrackPerf/all
	$(CMAKE_COMMAND) -E cmake_progress_start /global/homes/n/natalieb/TrackPerfWorkspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 packages/TrackPerf/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 packages/TrackPerf/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 packages/TrackPerf/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
packages/TrackPerf/CMakeFiles/TrackPerf.dir/rule:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 packages/TrackPerf/CMakeFiles/TrackPerf.dir/rule
.PHONY : packages/TrackPerf/CMakeFiles/TrackPerf.dir/rule

# Convenience name for target.
TrackPerf: packages/TrackPerf/CMakeFiles/TrackPerf.dir/rule

.PHONY : TrackPerf

# fast build rule for target.
TrackPerf/fast:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/build
.PHONY : TrackPerf/fast

src/FilterTracks.o: src/FilterTracks.cxx.o

.PHONY : src/FilterTracks.o

# target to build an object file
src/FilterTracks.cxx.o:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/FilterTracks.cxx.o
.PHONY : src/FilterTracks.cxx.o

src/FilterTracks.i: src/FilterTracks.cxx.i

.PHONY : src/FilterTracks.i

# target to preprocess a source file
src/FilterTracks.cxx.i:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/FilterTracks.cxx.i
.PHONY : src/FilterTracks.cxx.i

src/FilterTracks.s: src/FilterTracks.cxx.s

.PHONY : src/FilterTracks.s

# target to generate assembly for a file
src/FilterTracks.cxx.s:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/FilterTracks.cxx.s
.PHONY : src/FilterTracks.cxx.s

src/TrackHists.o: src/TrackHists.cxx.o

.PHONY : src/TrackHists.o

# target to build an object file
src/TrackHists.cxx.o:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TrackHists.cxx.o
.PHONY : src/TrackHists.cxx.o

src/TrackHists.i: src/TrackHists.cxx.i

.PHONY : src/TrackHists.i

# target to preprocess a source file
src/TrackHists.cxx.i:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TrackHists.cxx.i
.PHONY : src/TrackHists.cxx.i

src/TrackHists.s: src/TrackHists.cxx.s

.PHONY : src/TrackHists.s

# target to generate assembly for a file
src/TrackHists.cxx.s:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TrackHists.cxx.s
.PHONY : src/TrackHists.cxx.s

src/TrackPerfHistProc.o: src/TrackPerfHistProc.cxx.o

.PHONY : src/TrackPerfHistProc.o

# target to build an object file
src/TrackPerfHistProc.cxx.o:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TrackPerfHistProc.cxx.o
.PHONY : src/TrackPerfHistProc.cxx.o

src/TrackPerfHistProc.i: src/TrackPerfHistProc.cxx.i

.PHONY : src/TrackPerfHistProc.i

# target to preprocess a source file
src/TrackPerfHistProc.cxx.i:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TrackPerfHistProc.cxx.i
.PHONY : src/TrackPerfHistProc.cxx.i

src/TrackPerfHistProc.s: src/TrackPerfHistProc.cxx.s

.PHONY : src/TrackPerfHistProc.s

# target to generate assembly for a file
src/TrackPerfHistProc.cxx.s:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TrackPerfHistProc.cxx.s
.PHONY : src/TrackPerfHistProc.cxx.s

src/TruthHists.o: src/TruthHists.cxx.o

.PHONY : src/TruthHists.o

# target to build an object file
src/TruthHists.cxx.o:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TruthHists.cxx.o
.PHONY : src/TruthHists.cxx.o

src/TruthHists.i: src/TruthHists.cxx.i

.PHONY : src/TruthHists.i

# target to preprocess a source file
src/TruthHists.cxx.i:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TruthHists.cxx.i
.PHONY : src/TruthHists.cxx.i

src/TruthHists.s: src/TruthHists.cxx.s

.PHONY : src/TruthHists.s

# target to generate assembly for a file
src/TruthHists.cxx.s:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(MAKE) $(MAKESILENT) -f packages/TrackPerf/CMakeFiles/TrackPerf.dir/build.make packages/TrackPerf/CMakeFiles/TrackPerf.dir/src/TruthHists.cxx.s
.PHONY : src/TruthHists.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TrackPerf"
	@echo "... src/FilterTracks.o"
	@echo "... src/FilterTracks.i"
	@echo "... src/FilterTracks.s"
	@echo "... src/TrackHists.o"
	@echo "... src/TrackHists.i"
	@echo "... src/TrackHists.s"
	@echo "... src/TrackPerfHistProc.o"
	@echo "... src/TrackPerfHistProc.i"
	@echo "... src/TrackPerfHistProc.s"
	@echo "... src/TruthHists.o"
	@echo "... src/TruthHists.i"
	@echo "... src/TruthHists.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /global/homes/n/natalieb/TrackPerfWorkspace && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

